export const MOVIE_ADD_TO_FAVORITE = 'MOVIE_ADD_TO_FAVORITE';
export const MOVIE_REMOVE_FROM_FAVORITE = 'MOVIE_REMOVE_FROM_FAVORITE';

export const MOVIE_FETCH_INIT = 'MOVIE_FETCH_INIT';
export const MOVIE_FETCH_SUCCESS = 'MOVIE_FETCH_SUCCESS';
export const MOVIE_FETCH_FAIL = 'MOVIE_FETCH_FAIL';

export const MOVIELIST_FETCH_INIT = 'MOVIELIST_FETCH_INIT';
export const MOVIELIST_FETCH_SUCCESS = 'MOVIELIST_FETCH_SUCCESS';
export const MOVIELIST_FETCH_FAIL = 'MOVIELIST_FETCH_FAIL';

export const SIMILARLIST_FETCH_INIT = 'SIMILARLIST_FETCH_INIT';
export const SIMILARLIST_FETCH_SUCCESS = 'SIMILARLIST_FETCH_SUCCESS';
export const SIMILARLIST_FETCH_FAIL = 'SIMILARLIST_FETCH_FAIL';
