export const MOVIE_ADD_TO_FAVORITE = 'MOVIE_ADD_TO_FAVORITE';
export const MOVIE_REMOVE_FROM_FAVORITE = 'MOVIE_REMOVE_FROM_FAVORITE';

export const MOVIE_FETCH_INIT = 'MOVIE_FETCH_INIT';
export const MOVIE_FETCH_START = 'MOVIE_FETCH_START';
export const MOVIE_FETCH_SUCCESS = 'MOVIE_FETCH_SUCCESS';
export const MOVIE_FETCH_FAIL = 'MOVIE_FETCH_FAIL';

export const MOVIE_LIST_FETCH_INIT = 'MOVIE_LIST_FETCH_INIT';
export const MOVIE_LIST_FETCH_START = 'MOVIE_LIST_FETCH_START';
export const MOVIE_LIST_FETCH_SUCCESS = 'MOVIE_LIST_FETCH_SUCCESS';
export const MOVIE_LIST_FETCH_FAIL = 'MOVIE_LIST_FETCH_FAIL';

export const RECOMMEND_MOVIES_FETCH_START = 'RECOMMEND_MOVIES_FETCH_START';
export const RECOMMEND_MOVIES_FETCH_SUCCESS = 'RECOMMEND_MOVIES_FETCH_SUCCESS';
export const RECOMMEND_MOVIES_FETCH_FAIL = 'RECOMMEND_MOVIES_FETCH_FAIL';

export const SIMILAR_MOVIES_FETCH_START = 'SIMILAR_MOVIES_FETCH_START';
export const SIMILAR_MOVIES_FETCH_SUCCESS = 'SIMILAR_MOVIES_FETCH_SUCCESS';
export const SIMILAR_MOVIES_FETCH_FAIL = 'SIMILAR_MOVIES_FETCH_FAIL';

